name: lint-and-build
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: true
    - name: Setup eslint reviewer
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        eslint_flags: 'src/**/*.{ts,js,tsx,jsx}'
    - name: Copy config files
      run: cp .env.example .env
    - name: Eslint
      run: pnpm lint
    - name: Build test
      run: pnpm build
